email_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'email_manager'

urlpatterns = [
    path('', views.EmailAccountsListView.as_view(), name="email_address_list"),
    path('create/', views.EmailAccountCreate.as_view(), name="email_address_create"),
    path('<int:pk>/', views.EmailAccountUpdate.as_view(), name="email_address_update"),
    path('<int:pk>/delete/', views.EmailAccountDelete.as_view(), name="email_address_delete"),
    path('gmail-auth/', views.GmailAuthRedirectView.as_view(), name="gmail_auth"),
    path('oauth2callback/', views.OAuth2CallbackRedirectView.as_view(), name="oauth2callback"),
    path('emails-list/', views.EmailsListView.as_view(), name="email_list"),
    path('email-content/', views.EmailContentView.as_view(), name="email_content"),
]

job_application_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from email_manager.gmail_api_auth_files.authentication_views import oauth2callback

urlpatterns = [
    path('', include('application_manager.homepage_urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user_accounts.urls')),
    path('application/', include('application_manager.urls')),
    path('email/', include('email_manager.urls')),
]

email_manager/views.py
from django.urls import reverse_lazy
from django.views.generic import *
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.core.exceptions import ValidationError
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import *
from .get_emails import *
from .get_emails_api import *
from .forms import *
from .gmail_api_auth_files import authentication_views
from email_manager.old_gmail_api_auth_files.api_emails_list import *
import json
import imaplib

# Create your views here.


class EmailAccountsListView(LoginRequiredMixin, ListView):
    model = EmailAddress
    template_name = "email_manager/email-address-list.html"
    context_object_name = 'email_addresses'

    def get_queryset(self):
        queryset = super(EmailAccountsListView, self).get_queryset().filter(user=self.request.user)
        return queryset


class EmailAccountCreate(LoginRequiredMixin, CreateView):
    model = EmailAddress
    fields = ["address", "last_checked_date"]
    template_name = "email_manager/email-address-form.html"
    success_url = reverse_lazy("email_manager:email_address_list")

    # Overriden so the "last_checked_date" widget is an HTML date input field
    def get_form(self, form_class=None):
        form = super(EmailAccountCreate, self).get_form()
        form.fields['last_checked_date'].widget = CustomDateInput()
        return form

    # Overridden in order to set the new application's user to the current user
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class EmailAccountUpdate(LoginRequiredMixin, UpdateView):
    model = EmailAddress
    fields = ["address", "last_checked_date"]
    template_name = "email_manager/email-address-form.html"
    success_url = reverse_lazy("email_manager:email_address_list")

    # Overriden so the "last_checked_date" widget is an HTML date input field
    def get_form(self, form_class=None):
        form = super(EmailAccountUpdate, self).get_form()
        form.fields['last_checked_date'].widget = CustomDateInput()
        return form

    def get_queryset(self):
        return super(EmailAccountUpdate, self).get_queryset().filter(user=self.request.user)


class EmailAccountDelete(LoginRequiredMixin, DeleteView):
    model = EmailAddress
    # fields = ["address"]
    template_name = "email_manager/email-address-delete-form.html"
    success_url = reverse_lazy("email_manager:email_address_list")

    def get_queryset(self):
        return super(EmailAccountDelete, self).get_queryset().filter(user=self.request.user)


# Not a complete "Formview", as if the email address is a gmail address, GET-ing this view will redirect to the
# Google Auth Page, which will then redirect to the EmailsListView
class EmailFormView(LoginRequiredMixin, FormView):
    template_name = "email_manager/email-form.html"
    success_url = reverse_lazy('email_manager:email_list')

    def get_form_class(self):
        # if emails are retrieved from the Gmail API, password is unnecessary
        if self.email_from_api:
            return ApiEmailForm
        return EmailForm

    def get(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data(**kwargs)

        if self.email_addr is not None:
            form.initial = {"gmail_email": self.email_addr}
            # if email; address is found in database, pre-populate 'Emails Since'
            # field with 'Last Checked Date' field value
            try:
                email_addr_object = EmailAddress.objects.get(address=self.email_addr)
                form.initial["emails_since"] = email_addr_object.last_checked_date
            except Exception as e:
                pass

        context['form'] = form
        return self.render_to_response(context)

    def dispatch(self, request, *args, **kwargs):
        # Check if emails can be retrieved from API or not.
        # If yes, use ApiEmailForm and get emails from API,
        # otherwise use EmailForm and get emails using plain Python libraries.

        if not CustomCredentialsModel.objects.filter(user=request.user).exists():
            return authentication_views.authorize(request)

        # To do: clean up
        try:
            self.email_addr = self.request.GET["email_addr"]
            self.email_from_api = self.email_addr in GMAIL_API_EMAILS
        except KeyError:
            self.email_addr = None
            self.email_from_api = False

        return super(EmailFormView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        # Get email, pswd, since_date, use them to get emails
        email_address = form.cleaned_data['gmail_email']
        if not self.email_from_api:
            pswd = form.cleaned_data['password']
        else:
            pswd = ""
        date_from = form.cleaned_data['emails_since']

        # If authentication fails, redirect to email login page with prepopulated form
        # (by returning self.form_invalid(form)) and display "Invalid credentials" error message
        try:
            if self.email_from_api:
                emails_list = get_emails_api(email_address, date_from)
            else:
                emails_list = get_emails(email_address, pswd, date_from)
        except imaplib.IMAP4.error as e:
            credens_error = ValidationError("Invalid credentials", code="invalid_credens")
            form.add_error(None, credens_error)
            return self.form_invalid(form)

        # Serialize emails list to JSON for adding to session dict
        emails_json = json.dumps(emails_list, cls=EmailEncoder)
        self.request.session['emails'] = emails_json

        # Return Httpresponse:
        return super().form_valid(form)


class GmailAuthRedirectView(LoginRequiredMixin, RedirectView):
    url = "/"


class OAuth2CallbackRedirectView(LoginRequiredMixin, RedirectView):
    url = "/"


class EmailsListView(LoginRequiredMixin, TemplateView):
    template_name = "email_manager/emails-list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            emails_json = self.request.session['emails']

            # Un-serialize JSON email list, back to Python list for use in template context
            emails_list = json.loads(emails_json, object_hook=email_decoder)
        except:
            emails_list = []
        context['emails'] = emails_list

        return context


class EmailContentView(LoginRequiredMixin, TemplateView):
    template_name = "email_manager/email-content.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        emails_json = self.request.session['emails']
        #del self.request.session['emails']

        # Un-serialize JSON email list, back to Python list
        emails_list = json.loads(emails_json, object_hook=email_decoder)
        email_to_display_id = self.request.GET["email-id"]
        email_to_display = None
        for email in emails_list:
            if email.id == email_to_display_id:
                email_to_display = email

        context['email'] = email_to_display

        return context

email_manager/views/email_addr_views.py
from django.urls import reverse_lazy
from django.views.generic import *
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.core.exceptions import ValidationError
from django.contrib.auth.mixins import LoginRequiredMixin
from ..models import *
from ..get_emails import *
from ..get_emails_api import *
from ..forms import *
from ..gmail_api_auth_files import authentication_views
from email_manager.old_gmail_api_auth_files.api_emails_list import *
import json
import imaplib

# Create your views here.


class EmailAccountsListView(LoginRequiredMixin, ListView):
    model = EmailAddress
    template_name = "email_manager/email-address-list.html"
    context_object_name = 'email_addresses'

    def get_queryset(self):
        queryset = super(EmailAccountsListView, self).get_queryset().filter(user=self.request.user)
        return queryset


class EmailAccountCreate(LoginRequiredMixin, CreateView):
    model = EmailAddress
    fields = ["address", "last_checked_date"]
    template_name = "email_manager/email-address-form.html"
    success_url = reverse_lazy("email_manager:email_address_list")

    # Overriden so the "last_checked_date" widget is an HTML date input field
    def get_form(self, form_class=None):
        form = super(EmailAccountCreate, self).get_form()
        form.fields['last_checked_date'].widget = CustomDateInput()
        return form

    # Overridden in order to set the new application's user to the current user
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class EmailAccountUpdate(LoginRequiredMixin, UpdateView):
    model = EmailAddress
    fields = ["address", "last_checked_date"]
    template_name = "email_manager/email-address-form.html"
    success_url = reverse_lazy("email_manager:email_address_list")

    # Overriden so the "last_checked_date" widget is an HTML date input field
    def get_form(self, form_class=None):
        form = super(EmailAccountUpdate, self).get_form()
        form.fields['last_checked_date'].widget = CustomDateInput()
        return form

    def get_queryset(self):
        return super(EmailAccountUpdate, self).get_queryset().filter(user=self.request.user)


class EmailAccountDelete(LoginRequiredMixin, DeleteView):
    model = EmailAddress
    # fields = ["address"]
    template_name = "email_manager/email-address-delete-form.html"
    success_url = reverse_lazy("email_manager:email_address_list")

    def get_queryset(self):
        return super(EmailAccountDelete, self).get_queryset().filter(user=self.request.user)

email_manager/views/email_retrieve_views.py
from django.shortcuts import redirect
from django.views.generic import *
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login
from ..models import *
from ..get_emails_api import *
import json

import google.oauth2.credentials
import google_auth_oauthlib.flow
import googleapiclient.discovery


# The name of the directory containing the clients secret file
CLIENT_SECRETS_DIR_NAME = "gmail_api_auth_files"
# The name of a file that contains the OAuth 2.0 information for this application, including its client_id and
# client_secret.
CLIENT_SECRETS_FILE_NAME = "client_secret.json"

current_dir = os.path.dirname(os.path.abspath(__file__))
# print("Current dir:", current_dir)
parent_dir = os.path.join(current_dir, os.pardir)
# print("Parent dir:", parent_dir)
client_secrets_dir = os.path.join(parent_dir, CLIENT_SECRETS_DIR_NAME)
# print("File dir:", client_secrets_dir)
client_secrets_file = os.path.join(client_secrets_dir, CLIENT_SECRETS_FILE_NAME)
# print("File dir:", client_secrets_file)

# This OAuth 2.0 access scope allows for full read/write access to the
# authenticated user's account and requires requests to use an SSL connection.
SCOPES = ['https://www.googleapis.com/auth/gmail.readonly']
API_SERVICE_NAME = 'gmail'
API_VERSION = 'v1'


# Create your views here.


class GmailAuthRedirectView(LoginRequiredMixin, RedirectView):
    # url = "/"

    def authorize(self, request):

        # Create flow instance to manage the OAuth 2.0 Authorization Grant Flow steps.
        flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(
            client_secrets_file, scopes=SCOPES)

        flow.redirect_uri = 'http://localhost:8000/email/oauth2callback/'

        authorization_url, state = flow.authorization_url(
            # Enable offline access so that you can refresh an access token without
            # re-prompting the user for permission. Recommended for web server apps.
            access_type='offline',
            # Enable incremental authorization. Recommended as a best practice.
            include_granted_scopes='true')

        # Setting redirect url to authorization url.
        self.url = authorization_url

        # Store the state so the callback can verify the auth server response.
        user_state = CustomStateModel(user=request.user, state=state)
        user_state.save()

        print("New state should be:" + state)
        request.session['state'] = state
        print("Session state after set is:" + request.session['state'])
        request.session['next'] = request.get_full_path()
        print("Next:", request.session['next'])

    def dispatch(self, request, *args, **kwargs):
        self.authorize(request)
        self.url = self.url.replace('%', '%%')
        return super(GmailAuthRedirectView, self).dispatch(request, *args, **kwargs)


class OAuth2CallbackRedirectView(LoginRequiredMixin, RedirectView):
    url = "/"

    def get_redirect_url(self, *args, **kwargs):
        # Specify the state when creating the flow in the callback so that it can
        # verified in the authorization server response.

        print("USERNAME:", self.request.user.username)
        login(self.request, self.request.user)
        print(self.request.user.is_authenticated)
        state = CustomStateModel.objects.get(user=self.request.user).state
        print("Session state after callback is:" + state)

        flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(
            client_secrets_file, scopes=SCOPES, state=state)

        # DO NOT REMOVE THIS
        flow.redirect_uri = 'http://localhost:8000/email/oauth2callback/'

        # Use the authorization server's response to fetch the OAuth 2.0 tokens.
        authorization_response = self.request.build_absolute_uri()
        print("Auth response:" + authorization_response)
        flow.fetch_token(authorization_response=authorization_response)

        # Store credentials in the session.
        # ACTION ITEM: In a production app, you likely want to save these
        #              credentials in a persistent database instead.
        credentials = flow.credentials
        self.request.session['credentials'] = credentials_to_dict(credentials)
        # user_credens = CustomCredentialsModel()
        print("These are the credentials:\n", str(self.request.session['credentials']))

        print("Redirecting to after auth: ", self.request.session['next'])
        return super(OAuth2CallbackRedirectView, self).get_redirect_url(*args, **kwargs)


class EmailsListView(LoginRequiredMixin, TemplateView):
    template_name = "email_manager/emails-list.html"

    def dispatch(self, request, *args, **kwargs):
        # If not authenticated, redirect to Gmail Auth Redirect View
        if 'credentials' not in self.request.session:
            return redirect(reverse('gmail_auth'))
        return super(EmailsListView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            emails_json = self.request.session['emails']

            # Un-serialize JSON email list, back to Python list for use in template context
            emails_list = json.loads(emails_json, object_hook=email_decoder)
        except:
            emails_list = []
        context['emails'] = emails_list

        return context


class EmailContentView(LoginRequiredMixin, TemplateView):
    template_name = "email_manager/email-content.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        emails_json = self.request.session['emails']
        #del self.request.session['emails']

        # Un-serialize JSON email list, back to Python list
        emails_list = json.loads(emails_json, object_hook=email_decoder)
        email_to_display_id = self.request.GET["email-id"]
        email_to_display = None
        for email in emails_list:
            if email.id == email_to_display_id:
                email_to_display = email

        context['email'] = email_to_display

        return context


def credentials_to_dict(credentials):
    return {'token': credentials.token,
            'refresh_token': credentials.refresh_token,
            'token_uri': credentials.token_uri,
            'client_id': credentials.client_id,
            'client_secret': credentials.client_secret,
            'scopes': credentials.scopes}

email_manager/templates/email_manager/email-address-delete-form.html
{% extends 'application_manager/base.html' %}

{% block body %}

  <div class="container">

    <form method="POST">
      {% csrf_token %}
      <br />

      <p>
        Are you sure you want to delete the following email address?
        <br />
        <br />
        {{ object }}
      </p>

      <br />

      <input type="submit" value="Delete" class="btn btn-danger btn-sm"/>
      <a href="{% url 'email_manager:email_address_list' %}"><button type="button" class="btn btn-secondary btn-sm">Cancel </button></a>

    </form>
  </div>

{% endblock %}

email_manager/templates/email_manager/email-address-form.html
{% extends 'application_manager/base.html' %}

{% block body %}

  <div class="container">
    <br />
    <form method="POST">
      {% csrf_token %}
        <table>
          {{ form.as_table }}
        </table>
        <br />
      <input type="submit" class="btn btn-success btn-sm" value="Save" />
      <a href="{% url 'email_manager:email_address_list' %}"><button type="button" class="btn btn-secondary btn-sm">Cancel </button></a>

    </form>
  </div>

{% endblock %}

email_manager/templates/email_manager/email-address-list.html
{% extends 'application_manager/base.html' %}

{% block body %}

  <div class="container">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'application_manager/style.css' %}">
    <br />
    <h2> Email Addresses </h2>
    <br />
    <!--<table class="table" id="apps-table">-->
    <form action="{% url 'email_manager:gmail_auth' %}">
      <table class="table table-striped table-bordered table-sm">
        <thead class="thead thead-dark">
          <tr>
            <th>
              Email Address
            </th>
            <th>
            </th>
            <th>
            </th>
            <th>
            </th>
          </tr>
        </thead>
        <tbody>
          {% for email_address in email_addresses %}
            <tr>
              <td>
                {{ email_address.address }}
              </td>
              <td>
                <!--<a href="#"><button type="button" class="btn btn-primary btn-sm">Get Emails</button></a>-->
                <button type="submit" name="email_addr" value="{{ email_address.address }}" class="btn btn-primary btn-sm"> Get Emails </button>
              </td>
              <td>
                <a href="{% url 'email_manager:email_address_update' email_address.pk %}"><button type="button" class="btn btn-info btn-sm">Edit</button></a>
              </td>
              <td>
                <a href="{% url 'email_manager:email_address_delete' email_address.pk %}"><button type="button" class="btn btn-danger btn-sm">Delete</button></a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </form>

    <br />
    <a href="{% url 'email_manager:email_address_create' %}"><button type="button" class="btn btn-primary"> Add email address </button></a>
    <br />
    <br />

  </div>

{% endblock %}

email_manager/templates/email_manager/email-content.html
{% extends 'application_manager/base.html' %}

{% block body %}

  <div class="container">
    <br />

    <a href="{% url 'email_manager:email_list' %}"><button class="btn btn-secondary btn-sm">Back to emails list</button></a>

    <br />
    <br />

    <table>
      <tr>
        <td>
        <h3> Sender: </h3>
          </td>
        <td>
          <h3>{{ email.from_email }}</h3>
        </td>
      </tr>
      <tr>
        <td>
          <h3> Subject: </h3>
        </td>
        <td>
          <h3> {{ email.subject }}</h3>
        </td>
      </tr>
      <tr>
        <td>
          <h3> Date: &nbsp; </h3>
        </td>
        <td>
          <h3> {{ email.date }} </h3>
        </td>
      </tr>
    </table>

    <h3> Message: </h3>
    {% autoescape off %}
      {{ email.content }}
    {% endautoescape %}

  </div>

{% endblock %}

email_manager/templates/email_manager/email-form.html
{% extends 'application_manager/base.html' %}

{% block body %}

  <div class="container">
    <br />
    <form method="POST">
      {% csrf_token %}
        <table>
          {{ form.as_table }}
        </table>
        <br />
      <input type="submit" class="btn btn-success btn-sm" value="Get emails" />
    </form>
  </div>

{% endblock %}

email_manager/templates/email_manager/emails-list.html
{% extends 'application_manager/base.html' %}

{% block body %}

  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'email_manager/style.css' %}">

  <div class="container">

    <br />
    <h2> Emails </h2>
    <br />

    <form action="{% url 'email_manager:email_content' %}">
      <table class="table table-striped table-bordered table-sm">
        <thead class="thead thead-dark">
          <tr>
            <th>
              Sender
            </th>
            <th>
              Subject
            </th>
            <th>
              Date
            </th>
            <th>
              Message
            </th>
            <th>
            </th>
          </tr>
        </thead>
        <tbody>
          {% for email in emails %}
            <tr>
              <td>
                {{ email.from_email }}
              </td>
              <td>
                {{ email.subject }}
              </td>
              <td>
                {{ email.date }}
              </td>
              <td>
                {{ email.snippet }}
              </td>
              <td>
                <button type="submit" name="email-id" value="{{ email.id }}" class="btn btn-info btn-sm"> View </button>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </form>

  </div>

{% endblock %}