application_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'application_manager'

urlpatterns = [
    path('', views.ApplicationsListView.as_view(), name='application_list'),
    path('create/', views.ApplicationCreate.as_view(), name='application_create'),
    path('<int:pk>/', views.ApplicationUpdate.as_view(), name='application_update'),
    path('<int:pk>/delete/', views.ApplicationDelete.as_view(), name='application_delete'),
]

email_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'email_manager'

urlpatterns = [
    path('', views.EmailAccountsListView.as_view(), name="email_address_list"),
    path('create/', views.EmailAccountCreate.as_view(), name="email_address_create"),
    path('<int:pk>/', views.EmailAccountUpdate.as_view(), name="email_address_update"),
    path('<int:pk>/delete/', views.EmailAccountDelete.as_view(), name="email_address_delete"),
    path('gmail-auth/', views.GmailAuthRedirectView.as_view(), name="gmail_auth"),
    path('oauth2callback/', views.OAuth2CallbackRedirectView.as_view(), name="oauth2callback"),
    path('emails-list/', views.EmailsListView.as_view(), name="email_list"),
    path('email-content/', views.EmailContentView.as_view(), name="email_content"),
]

job_application_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from email_manager.gmail_api_auth_files.authentication_views import oauth2callback

urlpatterns = [
    path('', include('application_manager.homepage_urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user_accounts.urls')),
    path('application/', include('application_manager.urls')),
    path('email/', include('email_manager.urls')),
]

user_accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'user_accounts'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('manage/', views.ManageAccountView.as_view(), name="manage_account"),
    path('register/', views.UserCreate.as_view(), name="user_create"),
]

application_manager/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# from oauth2client.contrib.django_util.models import CredentialsField

# Create your models here.


class Application(models.Model):
    FULLTIME = 'Full-time'
    PARTTIME = 'Part-time'
    INTERNSHIP = 'Internship'
    PARTTIME_INTERNSHIP = 'Part-time intership'
    POSITION_TYPE_CHOICES = [
        (FULLTIME, 'Full-time'),
        (PARTTIME, 'Part-time'),
        (INTERNSHIP, 'Internship'),
        (PARTTIME_INTERNSHIP, 'Part-time intership'),
    ]

    NOT_APPLIED = "Didn't apply yet"
    IN_PROGRESS = 'In progress'
    APPLIED = 'Applied'
    INTERVIEWING = "Interviewing"
    ACCEPTED = 'Accepted'
    REJECTED = 'Rejected'
    OFFER_ACCEPTED = 'Offer accepted'
    OFFER_REJECTED = 'Offer rejected'
    STATUS_CHOICES = [
        (NOT_APPLIED, "Didn't apply yet"),
        (IN_PROGRESS, 'In progress'),
        (APPLIED, 'Applied'),
        (INTERVIEWING, "Interviewing"),
        (ACCEPTED, 'Accepted'),
        (REJECTED, 'Rejected'),
        (OFFER_ACCEPTED, "Offer accepted"),
        (OFFER_REJECTED, "Offer rejected"),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=100)
    position = models.CharField(max_length=40, null=True, blank=True)
    position_type = models.CharField(max_length=25, null=True, blank=True, choices=POSITION_TYPE_CHOICES)
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=20, null=True, blank=True)
    country = models.CharField(max_length=20)
    on_site = models.NullBooleanField(null=True, blank=True)
    application_link = models.CharField(max_length=256, null=True, blank=True)
    status = models.CharField(max_length=30, null=True, blank=True, choices=STATUS_CHOICES)
    lead = models.SmallIntegerField()
    email_tag = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return self.company_name + ' (' + self.position + ')'

    def get_absolute_url(self):
        return reverse('application_manager:application_list')


class EmailAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.EmailField()
    last_checked_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.address

    def get_absolute_url():
        return reverse('email_manager:emails_addresses_list')


class CustomStateModel(models.Model):
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    state = models.CharField(max_length=30)


class CustomCredentialsModel(models.Model):

    def __init__(self, user, flow_credentials):
        self.user = user
        self.token = flow_credentials.token
        self.refresh_token = flow_credentials.refrsh_token
        self.token_uri = flow_credentials.token_uri
        self.client_id = flow_credentials.client_id
        self.client_secret = flow_credentials.client_secret
        self.scopes = flow_credentials.scopes

    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    token = models.CharField(max_length=60)
    refresh_token = models.CharField(max_length=60)
    token_uri = models.CharField(max_length=150)
    client_id = models.CharField(max_length=60)
    client_secret = models.CharField(max_length=60)
    scopes = models.CharField(max_length=60)

application_manager/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

application_manager/views.py
from django.shortcuts import render
from django.views.generic import *
from django.urls import reverse_lazy
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from .models import *
from .forms import *
from .tables import *
# Create your views here.


APPLICATION_FORM_FIELDS = [
        'company_name',
        'position',
        'position_type',
        'city',
        'state',
        'country',
        'on_site',
        'application_link',
        'status',
        'lead'
]


class HomepageView(TemplateView):
    template_name = "application_manager/base.html"


# This class contains the model name, template name, and context_object_name.
# It's queryset is all the user's job applications (default is all instances of its model), and it returns
# an HttpResponse with all of the instances of its model
class ApplicationsListView(LoginRequiredMixin, ListView):
    model = Application
    template_name = "application_manager/index.html"
    context_object_name = 'applications'

    def get_queryset(self):
        queryset = super(ApplicationsListView, self).get_queryset().filter(user=self.request.user)
        return queryset


# when request.method == GET, returns HttpResponse of template containing empty
# form for its model. When request method is POST, saves it to database, and redirects
# to models absolute url (model.get_absolute_url)
class ApplicationCreate(LoginRequiredMixin, CreateView):
    model = Application
    fields = APPLICATION_FORM_FIELDS
    template_name_suffix = '-form'

    # Overridden in order to set the new application's user to the current user
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


# when request.method == GET, accepts pk parameter, and returns HttpResponse of template containing form
# for its model, populated with its objects values, for editing/updating.
# When request method is POST, saves it to database, and redirects
# to models absolute url (model.get_absolute_url)
class ApplicationUpdate(LoginRequiredMixin, UpdateView):
    model = Application
    fields = APPLICATION_FORM_FIELDS
    template_name_suffix = '-form'

    # Overridden in order to confirm that the request is coming from the owner of this resource
    def get_queryset(self):
        return super(ApplicationUpdate, self).get_queryset().filter(user=self.request.user)


# when request.method == GET, accepts pk parameter, and returns HttpResponse of template containing
# confirmation for deletion of its object.
# When request method is POST, deletes it from database, and redirects
# to success_url (NOT models absolute url)
class ApplicationDelete(LoginRequiredMixin, DeleteView):
    model = Application
    fields = APPLICATION_FORM_FIELDS
    template_name_suffix = '-delete-form'
    success_url = reverse_lazy('application_manager:application_list')

    # Overridden in order to confirm that the request is coming from the owner of this resource
    def get_queryset(self):
        return super(ApplicationDelete, self).get_queryset().filter(user=self.request.user)

application_manager/templates/application_manager/application-delete-form.html
{% extends 'application_manager/base.html' %}

{% block body %}

  <div class="container">

    <form method="POST">
      {% csrf_token %}
      <br />

      <p>
        Are you sure you want to delete the following application?
        <br />
        <br />
        {{ object }}
      </p>

      <br />

      <input type="submit" value="Delete" class="btn btn-danger btn-sm"/>
      <a href="{% url 'application_manager:application_list' %}"><button type="button" class="btn btn-secondary btn-sm">Cancel </button></a>

    </form>
  </div>

{% endblock %}

application_manager/templates/application_manager/application-form.html
{% extends 'application_manager/base.html' %}

{% block body %}
  <div class="container">

    <form method="POST">
      {% csrf_token %}

      <br />

      <table>
        {{ form.as_table }}
      </table>
      <br />
      <input type="submit" value="Save" class="btn btn-success btn-sm"/>
      <a href="{% url 'application_manager:application_list' %}"><button type="button" class="btn btn-secondary btn-sm">Cancel </button></a>
    </form>

  </div>

{% endblock %}

application_manager/templates/application_manager/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'homepage:homepage' %}">MyApps</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      {% with request.resolver_match.namespace as namespace %}
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <!--<li class="nav-item active">-->
            <li class="nav-item {% if namespace == 'homepage' %} active {% endif %}">
              <a class="nav-link" href="{% url 'homepage:homepage' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if namespace == 'application_manager' %} active {% endif %}">
              <a class="nav-link" href="{% url 'application_manager:application_list' %}">Applications</a>
            </li>
            <li class="nav-item {% if namespace == 'email_manager' %} active {% endif %}">
              <a class="nav-link" href="{% url 'email_manager:email_address_list' %}">Emails</a>
            </li>
            <!--<li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>-->
          </ul>
          <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'user_accounts:manage_account' %}"> Hello, {{ user.username }} </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'user_accounts:logout' %}">Logout</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'user_accounts:user_create' %}">Register</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'user_accounts:login' %}">Login</a>
                </li>
              {% endif %}
            </ul>
          </div>


          </ul>
        </div>
      {% endwith %}
    </nav>

    {% block body %}
      <div class="container">
        <br />
        <h2> Welcome to MyApps, a modern-day job application manager! </h2>
      </div>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

  </body>

</html>

application_manager/templates/application_manager/index.html
{% extends 'application_manager/base.html' %}

{% block body %}

  <div class="container">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'application_manager/style.css' %}">
    <br />
    <h2> Job Applications </h2>
    <br />
    <!--<table class="table" id="apps-table">-->
    <table class="table table-striped table-bordered table-sm">
      <thead class="thead thead-dark">
        <tr>
          <th>
            Company name
          </th>
          <th>
            Position
          </th>
          <th>
            Position type
          </th>
          <th>
            City
          </th>
          <th>
            State
          </th>
          <th>
            Country
          </th>
          <th>
            On site
          </th>
          <th>
            Application link
          </th>
          <th>
            Status
          </th>
          <th>
            Lead
          </th>
          <th>
          </th>
          <th>
          </th>
        </tr>
      </thead>
      <tbody>
        {% for app in applications %}
          <tr>
            <td>
              {{ app.company_name }}
            </td>
            <td>
              {{ app.position }}
            </td>
            <td>
              {{ app.position_type}}
            </td>
            <td>
              {{ app.city }}
            </td>
            <td>
              {{ app.state }}
            </td>
            <td>
              {{ app.country }}
            </td>
            <td>
              {{ app.on_site }}
            </td>
            <td>
              {{ app.application_link }}
            </td>
            <td>
              {{ app.status }}
            </td>
            <td>
              {{ app.lead }}
            </td>
            <td>
              <a href="{% url 'application_manager:application_update' pk=app.pk %}"><button type="button" class="btn btn-info btn-sm">Edit</button></a>
            </td>
            <td>
              <a href="{% url 'application_manager:application_delete' pk=app.pk %}"><button type="button" class="btn btn-danger btn-sm">Delete</button></a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <br />
    <a href="{% url 'application_manager:application_create' %}"><button type="button" class="btn btn-primary"> Add application </button></a>
    <br />
    <br />

  </div>

{% endblock %}